version: '3.8'
services:
  db:
    image: mongo:6.0.3
    env_file: .env
    volumes:
    - db:/data/db
    - ./entrypoints/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
    ports:
      - "27017:27017"

  redis:
    image: redis:6.2.0

  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app      
      - db
      - redis
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development
    entrypoint: ./entrypoints/sidekiq-entrypoint.sh

  webpacker:
    build: .
    ports:
      - '3035:3035'
    environment:
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    volumes:
      - .:/app
    entrypoint: ./entrypoints/webpack-entrypoint.sh

  app:
    tty: true
    stdin_open: true
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
      - webpacker
    links:
      - db
    volumes:
      - .:/app
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpacker
      WEBPACKER_DEV_SERVER_PORT: 3035

volumes:
  gem_cache:
  node_modules:
  db: