version: '3.8'
services:
  db:
    image: mongo:6.0.3
    restart: always
    ports:
      - "27017:27017"
  app:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/app
      