version: '3.8'
services:
  db:
    image: mongo:6.0.3
    restart: always
    ports:
      - "27017:27017"
  redis:
    image: redis:6.2.0
  
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app      
      - db
      - redis
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    env_file: .env
    environment:
      RAILS_ENV: development
    entrypoint: ./entrypoints/sidekiq-entrypoint.sh

  app:
    tty: true
    stdin_open: true
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/app

volumes:
  gem_cache:
  db_data:
  node_modules: