development:
  clients:
    default:
      database: <%= ENV["MONGODB"] %>
      hosts:
        - <%= "#{ENV["MONGOHOST"]}:#{ENV["MONGOPORT"]}" %>
      options:
        server_selection_timeout: 1
        user: <%= ENV["MONGOUSER"] %>
        password: <%= ENV["MONGOPASSWORD"] %>
  options:
production:
  clients:
    default:
      uri: <%= ENV['MONGO_URL'] || ENV['MONGODB_URI'] || ENV['MONGODB'] %>
test:
  clients:
    default:
      database: <%= ENV["MONGODB_TEST"] %>
      hosts:
        - <%= "#{ENV["MONGOHOST"]}:#{ENV["MONGOPORT"]}" %>
      options:
        user: <%= ENV["MONGOUSER"] %>
        password: <%= ENV["MONGOPASSWORD"] %>
