name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      db:
        image: mongo:6.0.3
        ports: ['27017:27017']

      redis:
        image: redis:6.2.0
    
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.4

      - name: Install Node dependencies
        run: yarn install

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.5
          bundler-cache: true

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: 6.0.3

      - name: Build and test with RSpec
        env:
          MONGOHOST: localhost
          MONGOUSER: ''
          MONGOPASSWORD: ''
          MONGODB_TEST: blog_test
          MONGOPORT: 27017
          MONGODB: blog
        run: |
          bundle exec rspec spec
